# Generated by Django 3.0.4 on 2020-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARTICULOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrearticulo', models.CharField(max_length=30)),
                ('seccion', models.CharField(max_length=20)),
                ('precioarticulo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CLIENTES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PEDIDOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerodepedido', models.IntegerField()),
                ('fechadepedido', models.DateField()),
                ('entrgapedido', models.BooleanField()),
            ],
        ),
    ]
